# Project information
site_name: 'Manual de Políticas y Procedimientos de Riesgo Tecnológico'
site_description: 'El Manual de Políticas y Procedimientos de Riesgo Tecnológico debe contener como mínimo los siguientes ITEMS:'
site_author: 'andrik Santos'
site_url: 'https://andriksantos.github.io/manual-politicas'

# Repository
repo_name: 'Manual Politicas'
repo_url: 'https://github.com/andriksantos/manual-politicas'

# Copyright
copyright: 'Copyright &copy; 2020 Andrik Santos'

#pages
pages:
  - Políticas y Riegos Tecnológico: index.md

# Configuration
theme:
  name: 'material'
  language: 'es'
  palette:
    primary: 'teal'
    accent: 'deep orange'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

extra:
  disqus: 'andrikSantos'

  # Customization
extra:
  social:
    - type: globe
      link: https://andriksantos.github.io/
    - type: github-alt
      link: https://github.com/andriksantos
    - type: facebook
      link: https://www.facebook.com/andrik.rsm
    - type: instagram
      link: https://www.instagram.com/andriksantos12/
    - type: linkedin
      link: https://www.linkedin.com/in/andriksantos/
    - type: twitter
      link: https://www.twitter.com/andrik_rsm

# Google Analytics
google_analytics:
  - 'UA-169388687-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true