# Project information
site_name: 'Manual de Políticas y Procedimientos de Riesgo Tecnológico'
site_description: 'El Manual de Políticas y Procedimientos de Riesgo Tecnológico debe contener como mínimo los siguientes ITEMS:'
site_author: 'andrik Santos'
site_url: 'https://andriksantos.github.io/manual-politicas'

# Repository
repo_name: 'Manual Politicas'
repo_url: 'https://github.com/andriksantos/manual-politicas'

# Copyright
copyright: 'Copyright &copy; 2020 Andrik Santos'

#pages
nav:
  - Políticas y Riegos Tecnológico: index.md
  - Codigo de conducta: code-of-conduct.md
  - Contribuir: contributing.md
  - Licencia: license.md
  - Agradecimiento: thanks.md

theme:
  name: 'material'
  language: 'es'
  palette:
    primary: 'teal'
    accent: 'deep orange'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

# Static files
static_templates:
    - 404.html

extra:
  disqus: 'andrikSantos'

  # Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://andriksantos.github.io/
      name: Go to my repository on github
    - icon: fontawesome/brands/twitter
      link: https://www.twitter.com/andrik_rsm/
      name: Follow me on twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/andriksantos/
      name: Follow me on linkedin
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/andriksantos1/
      name: andriksantos1 on instagram

# Google Analytics
google_analytics:
  - 'UA-169388687-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true